name: example
description: Example app for flutter_form_builder package
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder:
    path: ../
  form_builder_validators: ^11.1.2
  flutter_localizations:
    sdk: flutter
  intl: ">=0.20.0 <0.21.0"

dev_dependencies:
  flutter_lints: ">=6.0.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
